"""MD_table

Revision ID: 0ce9ab029714
Revises: 7678b6392e30
Create Date: 2021-05-15 22:26:23.106103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce9ab029714'
down_revision = '7678b6392e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MD__post', sa.Column('title', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MD__post', 'title')
    # ### end Alembic commands ###
