"""MD_table upgrade

Revision ID: 7678b6392e30
Revises: dcfdee6b9085
Create Date: 2021-05-15 21:43:39.012942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7678b6392e30'
down_revision = 'dcfdee6b9085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MD__post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MD__post_timestamp'), 'MD__post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MD__post_timestamp'), table_name='MD__post')
    op.drop_table('MD__post')
    # ### end Alembic commands ###
